"""schema inicial bangalo

Revision ID: 00028e1900f2
Revises: 
Create Date: 2026-07-21 03:17:53.584005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00028e1900f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicacao_financeira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'rendimento', 'resgate', name='tipo_aplicacao', native_enum=False), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aplicacao_financeira', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aplicacao_financeira_data'), ['data'], unique=False)

    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipo_categoria', native_enum=False), nullable=False),
    sa.Column('grupo', sa.String(length=80), nullable=False),
    sa.Column('subgrupo', sa.String(length=80), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'grupo', name='uq_categoria_nome_grupo')
    )
    op.create_table('config_sistema',
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('faturamento_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('aberto', sa.Boolean(), nullable=False),
    sa.Column('faturamento', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faturamento_diario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faturamento_diario_data'), ['data'], unique=True)

    op.create_table('faturamento_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('mes BETWEEN 1 AND 12', name='ck_mes_valido'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', name='uq_faturamento_ano_mes')
    )
    with op.batch_alter_table('faturamento_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faturamento_historico_ano'), ['ano'], unique=False)

    op.create_table('periodo_gorjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=60), nullable=False),
    sa.Column('ordem_quinzena', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('comissao_bruta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('percentual_encargos', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('meta_mes', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('meta_quinzena', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimativa_couvert_mes', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimativa_couvert_quinzena', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('aberto', 'fechado', name='status_periodo', native_enum=False), nullable=False),
    sa.CheckConstraint('ordem_quinzena IN (1, 2)', name='ck_ordem_quinzena'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', 'ordem_quinzena', name='uq_periodo_quinzena')
    )
    op.create_table('premissa_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('peso_mes_anterior', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('peso_media_historica', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('crescimento_alvo', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('peso_ter_qua', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('peso_qui_sex_dom', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('peso_sabado', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.CheckConstraint('peso_mes_anterior + peso_media_historica = 1.0', name='ck_pesos_somam_1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('percentual_rateio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('consultoria', 'gerencia', name='role_usuario', native_enum=False), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('comissao_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_gorjeta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'data', name='uq_comissao_dia')
    )
    with op.batch_alter_table('comissao_diaria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comissao_diaria_periodo_id'), ['periodo_id'], unique=False)

    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('apelido', sa.String(length=160), nullable=True),
    sa.Column('categoria_padrao_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_padrao_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('funcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('pontos_padrao', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'setor_id', name='uq_funcao_nome_setor')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('dados_antes', sa.JSON(), nullable=True),
    sa.Column('dados_depois', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_auditoria_timestamp'), ['timestamp'], unique=False)

    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('funcao_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('registro', sa.Enum('CLT', 'Por fora', 'CLT (rescisão)', 'CLT (férias)', 'Experiência', name='registro_colaborador', native_enum=False), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcao.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamento_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_fornecedor_id'), ['fornecedor_id'], unique=False)

    op.create_table('fechamento_gorjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('setor', sa.String(length=60), nullable=False),
    sa.Column('funcao', sa.String(length=60), nullable=False),
    sa.Column('registro', sa.String(length=30), nullable=False),
    sa.Column('pontos', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('dias_trabalhados', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('liquido_a_pagar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_gorjeta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fechamento_gorjeta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fechamento_gorjeta_periodo_id'), ['periodo_id'], unique=False)

    op.create_table('participacao_periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('dias_trabalhados_manual', sa.Integer(), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('desconto_motivo', sa.Enum('Perda', 'Avaria', 'Vale', 'Descontos', name='motivo_desconto', native_enum=False), nullable=True),
    sa.Column('desconto_observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_gorjeta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'colaborador_id', name='uq_participacao')
    )
    op.create_table('presenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_gorjeta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'colaborador_id', 'data', name='uq_presenca')
    )
    with op.batch_alter_table('presenca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presenca_periodo_id'), ['periodo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presenca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presenca_periodo_id'))

    op.drop_table('presenca')
    op.drop_table('participacao_periodo')
    with op.batch_alter_table('fechamento_gorjeta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fechamento_gorjeta_periodo_id'))

    op.drop_table('fechamento_gorjeta')
    with op.batch_alter_table('lancamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamento_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_lancamento_data'))
        batch_op.drop_index(batch_op.f('ix_lancamento_categoria_id'))

    op.drop_table('lancamento')
    op.drop_table('colaborador')
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_auditoria_timestamp'))

    op.drop_table('log_auditoria')
    op.drop_table('funcao')
    op.drop_table('fornecedor')
    with op.batch_alter_table('comissao_diaria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comissao_diaria_periodo_id'))

    op.drop_table('comissao_diaria')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('setor')
    op.drop_table('premissa_meta')
    op.drop_table('periodo_gorjeta')
    with op.batch_alter_table('faturamento_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faturamento_historico_ano'))

    op.drop_table('faturamento_historico')
    with op.batch_alter_table('faturamento_diario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faturamento_diario_data'))

    op.drop_table('faturamento_diario')
    op.drop_table('config_sistema')
    op.drop_table('categoria')
    with op.batch_alter_table('aplicacao_financeira', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aplicacao_financeira_data'))

    op.drop_table('aplicacao_financeira')
    # ### end Alembic commands ###
