"""lancamento origem/origem_id (integracao stone)

Revision ID: e57a93d7abf7
Revises: 00028e1900f2
Create Date: 2026-07-28 03:21:57.255902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57a93d7abf7'
down_revision = '00028e1900f2'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='manual' backfilla os lançamentos já existentes; a app
    # continua definindo o valor por código (default do model).
    with op.batch_alter_table('lancamento', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('origem', sa.String(length=20), nullable=False, server_default='manual')
        )
        batch_op.add_column(sa.Column('origem_id', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint('uq_lancamento_origem', ['origem', 'origem_id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lancamento_origem', type_='unique')
        batch_op.drop_column('origem_id')
        batch_op.drop_column('origem')

    # ### end Alembic commands ###
